### ISSUE TITLE
Make use of "includes" section and include only single file with all rules

### ISSUE THREAD

**Issue by TomasVotruba** [thecodingmachine/phpstan-strict-rules#6]
A bit of inspiration from [official phpstan extension](https://github.com/phpstan/phpstan-nette#usage):

**Instead of importin all files manually, just import them with one file:**

```yaml
# phpstan.neon (local in your project)
includes:
  - vendor/thecodingmachine/phpstan-strict-rules/phpstan-strict-rules.neon
```

```yaml
# phpstan-strict-rules.neon (in this package)
services:
  -
    class: TheCodingMachine\PHPStan\Rules\Exceptions\ThrowMustBundlePreviousExceptionRule
    tags:
      - phpstan.rules.rule
  -
    class: TheCodingMachine\PHPStan\Rules\Exceptions\DoNotThrowExceptionBaseClassRule
    tags:
      - phpstan.rules.rule
  -
    class: TheCodingMachine\PHPStan\Rules\Exceptions\EmptyExceptionRule
    tags:
      - phpstan.rules.rule
  -
    class: TheCodingMachine\PHPStan\Rules\TypeHints\MissingTypeHintInFunctionRule
    tags:
      - phpstan.rules.rule
  -
    class: TheCodingMachine\PHPStan\Rules\TypeHints\MissingTypeHintInMethodRule
    tags:
      - phpstan.rules.rule
```
